### ISSUE TITLE
-H option is missing

### ISSUE THREAD

**Issue by stettberger** [jeremy-compostella/pdfgrep#1]
I think you should add the -H option (add filename) by default. Otherwise, my grep mode did not identify the matches as matches.

https://github.com/jeremy-compostella/pdfgrep/blob/22d62f811c106f3162ffad6d41cdce85a9ca8be3/pdfgrep.el#L61

**Comment by jeremy-compostella** [comment]
Thanks for reporting this.  I have this into account, see https://github.com/jeremy-compostella/pdfgrep/commit/c21a2191d2d60788dd86c8c0fae78e3618ae32bb.
